# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e9add1c0ce016bf1c5892b31bf4d823664a4483de836e3503f62f2141adda7a90836ccac6a5fd8e83fcca8ff497e799eca350d7f8fb5d671a7c936ce7b168a4

test:
  secret_key_base: 1620aa0dd1cbecf738cd7b4ad5de4c04a7652fb1fd547e12eb7051ea5cf8495160939d43eda447ee8075069d016c1fba53f5dbaf2bdc8d462b832e7517ec62ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
